Parameters:
  KeyName:
    # https://github.com/awslabs/aws-cloudformation-templates/blob/8c8c4bf163c0356c67d9b8029fcba2d9a2962716/aws/services/VPC/VPC_EC2_Instance_With_Multiple_Static_IPAddresses.yaml#L10
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instance
    Type: AWS::EC2::KeyPair::KeyName
    ConstraintDescription: must be the name of an existing EC2 KeyPair.
  DatabaseName:
    Type: String
    Default: wordpress
  DatabaseUser:
    Type: String
    Default: wordpress
  DatabasePassword:
    Type: String
    NoEcho: true
  SSHIP:
    Type: String
    Default: 0.0.0.0/0
Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16